event/urls.py
from django.urls import path
from . import views

app_name = 'event'
urlpatterns = [
    path('', views.event_list, name='list'),
    path('<int:pk>/', views.event_detail, name='detail'),
    path('create/', views.event_create, name='create'),
]

study_meetup/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

def home_view(request):
    return redirect('/user/')

urlpatterns = [
    path('', home_view),
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('event/', include('event.urls')),
    path('user/', include('user.urls')),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('', views.user_home, name='home'),
    path('signin/', views.user_signin, name='signin'),
    path('signup/', views.user_signup, name='signup'),
    path('logout/', views.user_logout, name='logout'),
]

event/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext as _

from catalog.models import Course

EVENT_STATUS = (
    (1, _('Waiting')),
    (2, _('Approved')),
    (3, _('Archived')),
)


class Event(models.Model):
    name = models.CharField(max_length=128, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.PROTECT)
    status = models.IntegerField(choices=EVENT_STATUS, default=1)
    description = models.TextField()

    class Meta:
        verbose_name_plural = 'events'

    def __str__(self):
        return self.name

    def status_to_str(self):
        return [s[1] for s in EVENT_STATUS if s[0] == self.status][0]

    def set_status_approved(self):
        self.status = 2

    def set_status_archived(self):
        self.status = 3

    def is_waiting(self):
        return self.status == 1

    def is_approved(self):
        return self.status == 2

    def is_archived(self):
        return self.status == 3


class Proposition(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    datetime = models.DateTimeField()

    class Meta:
        verbose_name_plural = 'propositions'

    def __str__(self):
        return f'{self.event}'


class PropositionVote(models.Model):
    proposition = models.ForeignKey(Proposition, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    datetime = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('proposition', 'author')
        verbose_name_plural = 'proposition votes'

    def __str__(self):
        return f'{self.proposition} from {self.author}'

event/forms.py
from django import forms

from .models import Event
from catalog.models import Follower


def courses_for_student_as_choices(student):
    return [(f.course.id, f.course.name) for f in Follower.objects.filter(student=student)]


class EventForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    course = forms.ChoiceField()
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))

    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request
        self.fields['course'] = forms.ChoiceField(
            widget=forms.Select(attrs={'class': 'form-control'}),
            choices=courses_for_student_as_choices(self.request.user)
        )

    def clean_name(self):
        name = self.cleaned_data.get('name')
        events = Event.objects.filter(name=name)
        if events:
            raise forms.ValidationError('This name already exists')
        return name

event/views.py
from datetime import datetime

from django.http import Http404
from django.shortcuts import render, redirect
from django.contrib import messages
from django.utils.translation import gettext as _
from django.shortcuts import get_object_or_404
from django.db.models import Count
from django.utils.timezone import now

from catalog.models import Follower, Course

from .forms import EventForm
from .models import Event, Proposition, PropositionVote


def event_list(request):
    if not request.user.is_authenticated:
        return redirect('/user/')

    name = request.GET.get('name', '')
    status = int(request.GET.get('status', 0))

    followers = Follower.objects.filter(student=request.user)
    ids = [follower.course.id for follower in followers]

    if status != 0:
        events = Event.objects.filter(course__id__in=ids, name__icontains=name, status=status).order_by('-id')
    else:
        events = Event.objects.filter(course__id__in=ids, name__icontains=name).order_by('-id')

    return render(request, 'event/event_list.html', {'events': events})


def event_detail(request, pk):
    if not request.user.is_authenticated:
        redirect("/user/")

    event = get_object_or_404(Event, pk=pk)

    if request.method == "POST":
        if 'vote' in dict(request.POST) and event.is_waiting():
            proposition_id = int(request.POST['vote'])
            proposition_vote = PropositionVote.objects.filter(author=request.user, proposition_id=proposition_id)
            if not proposition_vote.exists():
                PropositionVote(proposition=list(Proposition.objects.filter(id=proposition_id))[0],
                                author=request.user,
                                datetime=now).save()
        
        if 'date' in dict(request.POST) and event.is_waiting():
            dt = datetime.strptime(request.POST['date'], '%Y-%m-%dT%H:%M')
            Proposition(author=request.user, event=event, datetime=dt).save()

        if 'close' in dict(request.POST) and event.is_waiting():
            if request.user != event.author:
                raise Http404()
            event.set_status_approved()
            event.save()
            messages.success(request, 'Event successfully closed.')

        if 'archive' in dict(request.POST) and event.is_approved():
            if request.user != event.author:
                raise Http404()
            event.set_status_archived()
            event.save()
            messages.success(request, 'Event successfully modified.')

    propositions = list(Proposition.objects.filter(event=event))
    votes = PropositionVote.objects.values('proposition').annotate(total=Count('proposition')).order_by('proposition')

    votes_as_dict = {}
    for vote in votes:
        votes_as_dict[vote['proposition']] = vote['total']
    
    for prop in propositions:
        if prop.id in votes_as_dict.keys():
            prop.votes = votes_as_dict[prop.id]
            prop.voted = PropositionVote.objects.filter(author=request.user, proposition_id=prop.id).exists()
        else:
            prop.votes = 0
            prop.voted = False

    propositions.sort(key=lambda x: x.votes, reverse=True)
    return render(request, 'event/event_detail.html', {'event': event, 'propositions': propositions})


def event_create(request):
    if request.method == 'POST':
        form = EventForm(request, request.POST)
        if form.is_valid():
            name = form.cleaned_data.get('name')
            course = form.cleaned_data.get('course')
            description = form.cleaned_data.get('description')

            course = Course.objects.get(pk=int(course))
            event = Event(name=name, author=request.user, course=course, description=description)
            event.save()

            messages.success(request, _('Event successfully created.'))
            return redirect('event:list')
    else:
        form = EventForm(request)
    return render(request, 'event/event_create.html', {'form': form})

event/templates/event/event_create.html
{% extends 'base.html' %}

{% block title %}Event create | {{ block.super }}{% endblock %}

{% block content %}
    <section id="event-create">
        <h3>Event create</h3>
        <form method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="row mb-3">
                    <label for="{{  field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label}}</label>
                    <div class="col-sm-10">
                        {{ field }}
                        {% if field.errors %}
                            <div class="text-danger">
                                {{ field.errors.as_text }}
                            </div>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </section>
{% endblock %}

event/templates/event/event_detail.html
{% extends 'base.html' %}

{% block title %}Event detail | {{ block.super }}{% endblock %}

{% block content %}
    <div class="container-md">
        <div class="row">
        <div class="col-12 col-md-6 d-flex flex-column my-2 py-3 border bg-light rounded text-dark">
            <div class="container-fluid my-2">
                <div class="small text-secondary">Name:</div> 
                <div class="big">{{event.name}}</div>
            </div>
            <div class="container-fluid my-2">
                <div class="small text-secondary">Author:</div> 
                <div> {{ event.author }}</div>
            </div>
            <div class="container-fluid my-2">
                <div class="small text-secondary">Course:</div> 
                <div> {{ event.course }}</div>
            </div>
            <div class="container-fluid my-2">
                <div class="small text-secondary">Status:</div>
                <div>
                    <span class="badge {% if event.status == 2 %} alert-success {% elif event.status == 3 %} alert-warning {% else %} alert-primary {% endif %}">{{ event.status_to_str }}</span>
                </div>
            </div>
            <div class="container-fluid my-2">
                <div class="small text-secondary">Description:</div> 
                <div> {{ event.description }}</div>
            </div>
            {% if event.author == request.user and event.status == 1 %}
            <div class="container-fluid my-2">
                <form method="POST">
                    {% csrf_token %}
                    <button class="btn btn-outline-danger" name="close">Close event</button>
                </form>
            </div>
            {% elif event.author == request.user and event.status == 2 %}
            <div class="container-fluid my-2">
                <form method="POST">
                    {% csrf_token %}
                    <button class="btn btn-outline-warning" name="archive">Archive event</button>
                </form>
            </div>
            {% endif %}
        </div>
        <div class="col-12 col-md-6 p-0 container-fluid">
            <form method="POST">
                {% csrf_token %}
                <div class="m-3">Suggested dates:</div>
                {% for proposition in propositions %}
                    <div class="mx-md-3 my-2 p-2 border {% if proposition == propositions.0 and event.status != 1 %} border-success {% endif %} rounded ">
                        <div class="row mx-2">
                            <div class="col-12 col-md-6">
                                <div>{{proposition.datetime}}</div>
                                <div class="text-secondary small">by {{proposition.author}}</div>
                            </div>
                            <div class="col-12 col-md-3">
                                <div>{{proposition.votes}}</div>
                                {% if proposition.votes == 1 %}
                                    <div class="text-secondary small">vote</div>
                                {% else %}
                                    <div class="text-secondary small">votes</div>
                                {% endif %}
                            </div>
                            {% if event.status == 1 %}
                            <div class="col-12 col-md-3 d-flex align-items-center">
                                {% if proposition.voted %}
                                    <button class="btn btn-outline-secondary disabled" name="vote" value="{{proposition.id}}">Voted</button>
                                {% else %}
                                    <button class="btn btn-outline-primary" name="vote" value="{{proposition.id}}">Vote</button>
                                {% endif %}
                            </div>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            </form>
        </div>
        {% if event.status == 1%}
        <div class="row">
            <div class="col-12 col-md-6 p-2 p-md-0">
                <form method="POST">
                    {% csrf_token %}
                    <div class="my-3">
                        <label class="form-label">Can't make it? Add your own date</label>
                        <input class="form-control" type="datetime-local" name="date"/>
                    </div>
                    <button class="btn btn-primary">Save</button>
                </form>
            </div>
        </div>
        {% endif %}
    </div>

{% endblock %}

event/templates/event/event_list.html
{% extends 'base.html' %}

{% block title %}Event list | {{ block.super }}{% endblock %}

{% block content %}
    <div>
        <div class="my-2">
            <a href="{% url 'event:create'%}">
                <button class="btn btn-outline-primary">
                    New event
                </button>
            </a>
        </div>
        <form method="get" class="row gy-2 gx-3 align-items-center">
            <div class="col-auto">
                <input type="text" class="form-control" name="name" placeholder="Analiza" value="{{ request.GET.name }}">
            </div>
            <div class="col-auto">
                <select class="form-select" name="status">
                    <option {% if request.GET.status == '0' %}selected{% endif %} value="0">Status</option>
                    <option {% if request.GET.status == '1' %}selected{% endif %} value="1">Waiting</option>
                    <option {% if request.GET.status == '2' %}selected{% endif %} value="2">Approved</option>
                    <option {% if request.GET.status == '3' %}selected{% endif %} value="3">Archived</option>
                </select>
            </div>
            <div class="col-auto">
                <button type="submit" class="btn btn-primary">Filter</button>
            </div>
        </form>
        {% for event in events %}
            <div class="border rounded my-2 p-2">
                <h5 class="m-2">{{event.name}}</h5>
                <div class="d-flex flex-column flex-md-row">
                    <div class="container-fluid">
                        <div class="small text-secondary">Course:</div>
                        <div> {{ event.course }}</div>
                    </div>
                    <div class="container-fluid">
                        <div class="small text-secondary">Author:</div> 
                        <div> {{ event.author }}</div>
                    </div>
                    <div class="container-fluid">
                        <div class="small text-secondary">Description:</div> 
                        <div> {{ event.description }}</div>
                    </div>
                    <div class="container-fluid">
                        <div class="small text-secondary">Status:</div>
                        <div> <span class="badge {% if event.status == 2 %} alert-success {% elif event.status == 3 %} alert-warning {% else %} alert-primary {% endif %}">{{ event.status_to_str }}</span></div>
                    </div>
                    <div class="container-fluid d-flex justify-content-start justify-content-md-end">
                        <a href="{% url 'event:detail' event.pk %}">
                            <button class="btn btn-primary my-2 px-4">Details</button>
                        </a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}