catalog/urls.py
from django.urls import path
from . import views

app_name = 'catalog'
urlpatterns = [
    path('', views.catalog_root, name='root'),
    path('course/', views.course_list, name='course_list'),
    path('disciplines/', views.discipline_list, name='discipline_list'),
    path('faculties/', views.faculties_list, name='faculties_list'),
    path('univiersities/', views.universities_list, name='universities_list')
]

event/urls.py
from django.urls import path
from . import views

app_name = 'event'
urlpatterns = [
    path('', views.event_list, name='list'),
    path('<int:pk>/', views.event_detail, name='detail'),
    path('create/', views.event_create, name='create'),
]

study_meetup/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

def home_view(request):
    return redirect('/user/')

urlpatterns = [
    path('', home_view),
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('event/', include('event.urls')),
    path('user/', include('user.urls')),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('', views.user_home, name='home'),
    path('signin/', views.user_signin, name='signin'),
    path('signup/', views.user_signup, name='signup'),
    path('logout/', views.user_logout, name='logout'),
]

common/templates/base.html
<!doctype html>
<html lang="pl">
<head>
    <meta charset="utf-8">
    <title>{% block title %}Study Meetup{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container-fluid bg-light">
        {% include 'navbar.html' %}
    </div>
    <div class="container">
        {% include 'messages.html' %}
        {% block content %}{% endblock %}
    </div>
</body>
</html>

common/templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

common/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light container">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'catalog:root' %}">Study Meetup</a>
        <button class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'event:list' %}" aria-current="page">Events</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'catalog:root' %}" aria-current="page">My subjects</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:logout' %}" aria-current="page">Logout ({{ request.user.username }})</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:signin' %}" aria-current="page">Signin</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:signup' %}" aria-current="page">Signup</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>